feat(build): outputting tests in the CI

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -48,3 +48,10 @@ jobs:
         run: npm run build --if-present
       - name: run test
         run: npm run test
+      - name: Unit Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure() # run this step even if previous step failed
+        with:
+          name: Unit Tests # Name of the check run which will be created
+          path: ./junit.xml # Path to test results
+          reporter: jest-junit # Format of test results
