feat(build): adding e2e tests back in

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -9,21 +9,17 @@ on:
 
 env:
   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  LAMBDA_USER: ${{ secrets.LAMBDA_USER }}
+  LAMBDA_KEY: ${{ secrets.LAMBDA_KEY }}
 jobs:
   lint:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
-      - uses: actions/cache@v2
-        with:
-          path: |
-            node_modules
-            **/node_modules
-          key: ${{ runner.os }}-${{ hashFiles('./package-lock.json') }}
-      - name: Use Node.js 16.x
-        uses: actions/setup-node@v2
+      - uses: actions/setup-node@v2
         with:
           node-version: 16.x
+          cache: "npm"
       - name: NPM install
         run: npm ci
       - name: Run lint
@@ -32,26 +28,39 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
-      - uses: actions/cache@v2
-        with:
-          path: |
-            node_modules
-            **/node_modules
-          key: ${{ runner.os }}-${{ hashFiles('./package-lock.json') }}
-      - name: Use Node.js 16.x
-        uses: actions/setup-node@v2
+      - uses: actions/setup-node@v2
         with:
           node-version: 16.x
+          cache: "npm"
       - name: NPM install
         run: npm ci
       - name: Run Build
         run: npm run build --if-present
       - name: run test
-        run: npm run test
+        run: npm run test:unit:ci
       - name: Unit Test Report
         uses: dorny/test-reporter@v1
         if: success() || failure() # run this step even if previous step failed
         with:
           name: Unit Tests # Name of the check run which will be created
           path: ./junit.xml # Path to test results
+          reporter: jest-junit # Format of test results
+  e2e:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v2
+      - uses: actions/setup-node@v2
+        with:
+          node-version: 16.x
+          cache: "npm"
+      - name: NPM install
+        run: npm ci
+      - name: Run E2E
+        run: npm run test:e2e
+      - name: E2E Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure() # run this step even if previous step failed
+        with:
+          name: E2E Tests # Name of the check run which will be created
+          path: ./results-e2e.xml # Path to test results
           reporter: jest-junit # Format of test results
